### ISSUE TITLE
Spawn bullets from moving node

### ISSUE THREAD

**Issue by Karlmit** [Moonzel/Godot-PerfBullets#4] opened 2023-10-08 20:20 UTC
I need to be able to spawn bullets from enemies that are able to move. 
Is it possible to spawn bullets from a node, without having all spawned bullets also be transformed with the parent? 

Maybe a solution could be a new property for the Spawner, for a location where the next bullet will be spawned?

**Comment by Moonzel** [comment] 2023-10-11 00:12
Thanks for bringing this to my attention. This was the intended behavior of the moveWithParent property when set to false, but there are clearly bugs. I will fix them ASAP!

**Comment by Karlmit** [comment] 2023-10-11 18:51
Alright cool! Sharing my test project just in case you would need it.  

The plugin otherwise looks awesome! Seems very well optimized checking the example scenes!
[Bullet_Test_2.zip](https://github.com/Moonzel/Godot-PerfBullets/files/12873598/Bullet_Test_2.zip)

**Comment by Moonzel** [comment] 2023-10-11 22:08
I have mostly solved the problem now! In a bit, I will update documentation and release the fix. Thanks for all of your help!

**Comment by Moonzel** [comment] 2023-10-12 03:30
The latest Update 1.1.1 solved this issue! Please make sure moveWithParent is set to false, and this should work as intended. I am closing this issue, and thanks for your help!

**Closed by Moonzel** 2023-10-12 03:30 UTC
